### ISSUE TITLE
APKs missing at the latest tags

### ISSUE THREAD

**Issue by IzzySoft** [ray-pH/Nabla-TypeMath-android#4]
Looks like you forgot to attach the APKs to the latest tag. Could you add them again, please (at least starting with the latest one)? Thanks!

**Comment by IzzySoft** [comment]
@ray-pH any chance?

**Comment by ray-pH** [comment]
Since v1.3, i originally want to update the latest version only into google play, i was too lazy to update the project in multiple places and i thought most people would just download it from google play anyway. But apparently there is demand for the APK here, so i've uploaded the APK for the latest release into github. cheers.

**Comment by IzzySoft** [comment]
Wonderful, thanks! To give you some background: Since August 2021, I've made [your app available here](https://apt.izzysoft.de/fdroid/index/apk/com.ph.nabla_typemath) for those without access to Google's walled garden. I'm not an Android dev, so I depend on the APK for that to be provided by the resp. projects (here: you). So now it will be updated again – and I thank you in the name of the people depending on this! :heart_eyes:

PS: If you want to link there (e.g. from the Readme), be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for that :wink:
